### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by yaowan233** [MaxOhn/rosu-pp-py#11]
rosu_pp_py v2.0.0
~~`from rosu_pp_py import GameMods`~~
~~ImportError: cannot import name 'GameMods' from 'rosu_pp_py'~~
Nevermind, I find out if I pass `[{'acronym': 'CL', 'settings': None}]` to mods will raise a `TypeError: kwarg 'mods': must be GameMods`
but will be fine if I pass `[{'acronym': 'CL'}]` to mods
maybe settings can be optional?

ps. by testing, it seems like "lazer" parameter is not having any effect in mania. If i set it to False, the score is still computed in lazer.

**Comment by MaxOhn** [comment]
> rosu_pp_py v2.0.0 ~`from rosu_pp_py import GameMods`~ ~ImportError: cannot import name 'GameMods' from 'rosu_pp_py'~ Nevermind, I find out if I pass `[{'acronym': 'CL', 'settings': None}]` to mods will raise a `TypeError: kwarg 'mods': must be GameMods` but will be fine if I pass `[{'acronym': 'CL'}]` to mods maybe settings can be optional?

Indeed `GameMods` isn't supposed to be imported, it's just an alias for certain forms they can be passed as. I can probably make that error at least a bit clearer. Being able to pass `None` for the settings also sounds sensible. Gamemod deserialization is quite the beast so I can't guarantee to make it possible but I'll look into it.

> ps. by testing, it seems like "lazer" parameter is not having any effect in mania. If i set it to False, the score is still computed in lazer.

Ahh I really forgot to pass the argument along to the calculation 🙈 Will fix this ASAP

**Comment by MaxOhn** [comment]
Fix released in `v2.0.1` 🎉
