### ISSUE TITLE
`maxCombo` does not appear in CalculateResult in standard mode.

### ISSUE THREAD

**Issue by kpei** [MaxOhn/rosu-pp-py#2]
I've tried getting the maxCombo from difficulty calculations but it doesn't seem to be appearing. I've played around with setting certain parameters in `ScoreParams` but it doesn't work.

`Calculator('map.osu').calculate(ScoreParams(mods = 64, acc = 95))`
```
[CalculateResult { mode: 0, stars: 2.206419431484571, pp: 8.579321639629624, ppAcc: 0.2866670049332536, ppAim: 5.292888710621588, ppFlashlight: 0.0, ppSpeed: 2.6194414266471324, aimStrain: 1.127623313479279, speedStrain: 0.9854881432720148, flashlightRating: 0.0, sliderFactor: 0.9768899991466172, ar: 6.6, cs: 3.0, hp: 2.0, od: 2.0, bpm: 262.4999999999999, clockRate: 1.5, nCircles: 52, nSliders: 99, nSpinners: 2 }]
```

**Comment by MaxOhn** [comment]
You're right, I forgot to add the max combo when displaying a calculation result oops, will fix that 👌 
You should still be able to access the maxCombo field though, it's just not displayed in the string format.

**Comment by MaxOhn** [comment]
Fix is released :)
