### ISSUE TITLE
pyo3 failed to build

### ISSUE THREAD

**Issue by TrueRou** [MaxOhn/rosu-pp-py#4]
It worked before, until i updated my repo recently
occured when pip install
![image](https://user-images.githubusercontent.com/30361160/220330538-ef87a488-a1d4-4de0-b29a-f31e95fe89d8.jpg)

**Comment by MaxOhn** [comment]
Might be that you need to update your rust version (`rustup update`).
Alternatively try cleaning rusts generated artifacts (`cargo clean`) to build from scratch.
Let me know if it still doesn't work after these.

**Comment by TrueRou** [comment]
> Might be that you need to update your rust version (`rustup update`). Alternatively try cleaning rusts generated artifacts (`cargo clean`) to build from scratch. Let me know if it still doesn't work after these.

I updated my rustup to stable-x86_64-unknown-linux-gnu unchanged - rustc 1.67.1 (d5a82bbd2 2023-02-07) and it still doesn't work

**Comment by MaxOhn** [comment]
And you did `cargo clean` too? If you have a `/target` folder with rust things inside you can try deleting that.
Maybe uninstalling the previous rosu-pp-py version through pip helps.

I can't reproduce it so it must be some older artifact that's interfering with your compilation.

**Comment by TrueRou** [comment]
> And you did `cargo clean` too? If you have a `/target` folder with rust things inside you can try deleting that. Maybe uninstalling the previous rosu-pp-py version through pip helps.
> 
> I can't reproduce it so it must be some older artifact that's interfering with your compilation.

Is the cargo base directory in the pip folder? I install rosupp with pip install. Im not quite sure where the folder is
